"""Regenerates scripts/fixtures/fake_secrets_sample.py — a local-only fixture
of FAKE credentials used to prove scan_secrets() actually detects something
(app.py in sl-rwl/test_1 has no real secrets to find).

The fixture itself is gitignored: its content matches the exact formats
GitHub's push protection scans for, so committing it risks a blocked push.
This generator is safe to commit because no line here contains a full,
contiguous secret-shaped string — each one is assembled from two pieces at
runtime. Run it whenever you need the fixture back:

    python scripts/generate_fake_secrets_fixture.py
"""
import os

FIXTURE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "fake_secrets_sample.py")

# Each fake secret is split into (prefix, body) so the full string never
# appears contiguously in this file's own source.
_GHP = ("ghp_", "0123456789abcdefghijklmnopqrstuvwxyz")
_GITHUB_PAT = ("github_pat_", "11ABCDEFG0123456789abcdefghijklmnopqrstuvwxyz1234567890")
_OPENAI = ("sk-", "ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890")
_AWS = ("AKIA", "ABCDEFGHIJKLMNOP")
_GOOGLE = ("AIza", "A1B2C3D4E5A1B2C3D4E5A1B2C3D4E5A1B2C")


def _join(pair: tuple) -> str:
    return pair[0] + pair[1]


def build_content() -> str:
    lines = [
        "# FAKE credentials for testing scan_secrets() only — none of these are real",
        "# keys, tokens, or accounts. Auto-generated by",
        "# scripts/generate_fake_secrets_fixture.py — do not hand-edit, do not commit",
        "# (already in .gitignore; these strings would trip GitHub push protection).",
        "",
        f'GITHUB_TOKEN = "{_join(_GHP)}"',
        f'GITHUB_FINE_GRAINED = "{_join(_GITHUB_PAT)}"',
        f'OPENAI_API_KEY = "{_join(_OPENAI)}"',
        f'AWS_ACCESS_KEY_ID = "{_join(_AWS)}"',
        f'GOOGLE_API_KEY = "{_join(_GOOGLE)}"',
        "",
        'password = "SuperSecretPassword123"',
        'api_key = "abcdef1234567890"',
        'secret = "this-is-not-really-secret-either"',
        "",
        "# A line that must NOT be flagged: no assignment, just a comment/example.",
        'print("set GITHUB_TOKEN as an environment variable, never hardcode it")',
        "",
    ]
    return "\n".join(lines)


def main():
    os.makedirs(os.path.dirname(FIXTURE_PATH), exist_ok=True)
    with open(FIXTURE_PATH, "w", encoding="utf-8") as f:
        f.write(build_content())
    print(f"wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
